########################################################################################
###################################### CONFIG FILE #####################################
########################################################################################

Username: STAG
Password: Melbourne
Scheme: https
Domain: jsonplaceholder.typicode.com
Fixtures: features/fixtures